<?php
	/**
	 * Every html email template must be inlined if it contains css. You can try any website online like this one https://htmlemail.io/inline/
	 * If your code requires php variables then you must use a namespace.
	 */
	namespace Core\Mail\Templates\Web2FA; 
?>

<!-- PreHeader. A preheader is a preview of the email content. It is recommended to keep it under 100 characters but up to 250 are allowed -->
<span class="preheader" style="color: transparent; display: none; height: 0; max-height: 0; max-width: 0; opacity: 0; overflow: hidden; visibility: hidden; width: 0;">
    <p>No comparta esta contraseña de un solo uso con nadie.</p>
</span>
<!-- END preHeader -->
    
<!-- MAIN CONTENT -->
<table class="wrapper" role="presentation" border="0" cellpadding="0" cellspacing="0" style="border-collapse: separate; min-width: 100%; box-sizing: border-box; padding: 20px; background: #ffffff; border-radius: 5px; width: 100%;" width="100%">
    <tr>
        <td style="font-family: sans-serif; font-size: 14px; vertical-align: top;" valign="top">	
            <p>A continuación se muestra su código de verificación de un solo uso</p><br>    
        
            <center>
                <h1>
                    <strong>
                        <?= Web2FAMail::$otp ?>
                    </strong>
                </h1>
            </center>
            <br>   
            <p>Este código de verificación caduca en 20 minutos.</p>

            <p>Si tiene algún problema con su cuenta, no dude en contactarnos.</p><br>
            
            <p>Si no fue usted, cambie su contraseña de inmediato para proteger su cuenta. Para mayor seguridad, recomendamos habilitar la verificación en dos pasos.</p>
        </td>
    </tr>
</table>
<!-- END MAIN CONTENT -->