<table class="footer" role="presentation" border="0" cellpadding="0" cellspacing="0" style="border-collapse: separate; min-width: 100%; clear: both; Margin-top: 10px; text-align: center; width: 100%;" width="100%" align="center">
    <tr>
        <td style="font-family: sans-serif; vertical-align: top; color: #9a9ea6; font-size: 12px; text-align: center;" align="center" valign="top">
            <!--Footer text goes here-->
        </td>
    </tr>
    <tr>
        <td style="font-family: sans-serif; vertical-align: top; color: #9a9ea6; font-size: 12px; text-align: center;" align="center" valign="top">
            <span style="color: #9a9ea6; font-size: 12px; text-align: center;">Powered by</span>
            <a href="https://nerdtrix.org" style="color: #9a9ea6; font-size: 12px; text-align: center; text-decoration: none;">
                Nerdtrix.org
            </a>
        </td>
    </tr>
</table>