<?php
	/**
	 * Every html email template must be inlined if it contains css. You can try any website online like this one https://htmlemail.io/inline/
	 * If your code requires php variables then you must use a namespace.
	 */
	namespace Core\Mail\Templates\NewDevice; 
?>

<!-- PreHeader. A preheader is a preview of the email content. It is recommended to keep it under 100 characters but up to 250 are allowed -->
<span class="preheader" style="color: transparent; display: none; height: 0; max-height: 0; max-width: 0; opacity: 0; overflow: hidden; visibility: hidden; width: 0;">
    <p>We noticed you recently tried to sign in to your account from a new device.</p>
</span>
<!-- END preHeader -->
    
<!-- MAIN CONTENT -->
<table class="wrapper" role="presentation" border="0" cellpadding="0" cellspacing="0" style="border-collapse: separate; min-width: 100%; box-sizing: border-box; padding: 20px; background: #ffffff; border-radius: 5px; width: 100%;" width="100%">
    <tr>
        <td style="font-family: sans-serif; font-size: 14px; vertical-align: top;" valign="top">	
            <p>We noticed you recently tried to sign in to your account from a new device.</p>
            <h4>A new login was attempted from the following</h4>
            <ul>
                <li><strong>Date:</strong> <?= NewDeviceMail::$date ?></li>
                <li><strong>Browser:</strong> <?= NewDeviceMail::$browser ?></li>
                <li><strong>Platform:</strong> <?= NewDeviceMail::$platform ?></li>
                <li><strong>IP Address:</strong> <?= NewDeviceMail::$ipAddress ?></li>
            </ul>
            <p>If this wasn't you, please change your password immediately to secure your account. For added security, we recommend enabling Two-Step Verification.</p><br>
            <h4>
                <strong>Why did we send this?</strong>
            </h4>
            <p>We didn't recognize this device or browser. You might receive this email again if you sign in from a new device or browser, you clear your cookies or you use your browser's private mode.</p>
        </td>
    </tr>
</table>
<!-- END MAIN CONTENT -->