<?php
	/**
	 * Every html email template must be inlined if it contains css. You can try any website online like this one https://htmlemail.io/inline/
	 * If your code requires php variables then you must use a namespace.
	 */
	namespace Core\Mail\Templates\NewDevice; 
?>

<!-- PreHeader. A preheader is a preview of the email content. It is recommended to keep it under 100 characters but up to 250 are allowed -->
<span class="preheader" style="color: transparent; display: none; height: 0; max-height: 0; max-width: 0; opacity: 0; overflow: hidden; visibility: hidden; width: 0;">
    <p>Hemos detectado que recientemente has intentado iniciar sesión en tu cuenta desde un nuevo dispositivo.</p>
</span>
<!-- END preHeader -->
    
<!-- MAIN CONTENT -->
<table class="wrapper" role="presentation" border="0" cellpadding="0" cellspacing="0" style="border-collapse: separate; min-width: 100%; box-sizing: border-box; padding: 20px; background: #ffffff; border-radius: 5px; width: 100%;" width="100%">
    <tr>
        <td style="font-family: sans-serif; font-size: 14px; vertical-align: top;" valign="top">	
            <p>Hemos detectado que recientemente has intentado iniciar sesión en tu cuenta desde un nuevo dispositivo.</p>
            <h4>Se intentó un nuevo inicio de sesión desde:</h4>
            <ul>
                <li><strong>Fecha:</strong> <?= NewDeviceMail::$date ?></li>
                <li><strong>Navegador:</strong> <?= NewDeviceMail::$browser ?></li>
                <li><strong>Plataforma:</strong> <?= NewDeviceMail::$platform ?></li>
                <li><strong>Dirección IP:</strong> <?= NewDeviceMail::$ipAddress ?></li>
            </ul>
            <p>Si no fue usted, cambie su contraseña de inmediato para proteger su cuenta. Para mayor seguridad, recomendamos habilitar la verificación en dos pasos.</p><br>
            <h4>
                <strong>¿Por qué enviamos este correo?</strong>
            </h4>
            <p>No hemos podido reconocer este dispositivo o navegador. Es posible que reciba este correo electrónico nuevamente si inicia sesión desde un nuevo dispositivo o navegador, borra sus cookies o usa el modo privado de su navegador.</p>
        </td>
    </tr>
</table>
<!-- END MAIN CONTENT -->