<?php
	/**
	 * Every html email template must be inlined if it contains css. You can try any website online like this one https://htmlemail.io/inline/
	 * If your code requires php variables then you must use a namespace.
	 */
	namespace Core\Mail\Templates\NewDevice; 

	#Translator instance
	$lang = new \Core\Language\Translator();	
?>

<!doctype html>
<html lang="en_US">
	<head>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width">
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<title><?= EZENV["APP_NAME"]; ?></title>
	</head>
	<style>
        @media only screen and (max-width: 620px) 
		{
            table[class=body] .container {
                padding: 0 !important;
                width: 100% !important;
            }

            table[class=body] .content {
                padding: 0 !important;
            }

            table[class=body] .wrapper {
                padding: 10px !important;
            }

            table[class=body] h1 {
                font-size: 28px !important;
                margin-bottom: 10px !important;
            }

            table[class=body] p,
            table[class=body] ul,
            table[class=body] ol,
            table[class=body] td,
            table[class=body] span,
            table[class=body] a {
                font-size: 16px !important;
            }
        }
    </style>

	<body style="background-color: #eaebed; font-family: sans-serif; -webkit-font-smoothing: antialiased; font-size: 14px; line-height: 1.4; margin: 0; padding: 0; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%;">
		<table class="body" role="presentation" border="0" cellpadding="0" cellspacing="0" style="border-collapse: separate; min-width: 100%; background-color: #eaebed; width: 100%;" width="100%" bgcolor="#eaebed">
			<tr>
				<td style="font-family: sans-serif; font-size: 14px; vertical-align: top;" valign="top">&nbsp;</td>

				<td class="container" style="font-family: sans-serif; font-size: 14px; display: block; max-width: 580px; padding: 10px; width: 580px; Margin: 0 auto;" width="580" valign="top">

					<!--Header-->
					<?php include(sprintf("%s%sheader.phtml", dirname(__DIR__, 1), DIRECTORY_SEPARATOR)); ?>
					<!--END Header-->

					<div class="content" style="box-sizing: border-box; display: block; Margin: 0 auto; max-width: 580px; padding: 10px;">

						<!-- PreHeader. A preheader is a preview of the email content. It is recommended to keep it under 100 characters but up to 250 are allowed -->
						<span class="preheader" style="color: transparent; display: none; height: 0; max-height: 0; max-width: 0; opacity: 0; overflow: hidden; visibility: hidden; width: 0;">
							<p>
                                <?= $lang->translate("your_account_has_been_locked")?>
                            </p>
						</span>
						<!-- END preHeader -->
							
						<!-- MAIN CONTENT -->
						<table class="wrapper" role="presentation" border="0" cellpadding="0" cellspacing="0" style="border-collapse: separate; min-width: 100%; box-sizing: border-box; padding: 20px; background: #ffffff; border-radius: 5px; width: 100%;" width="100%">
							<tr>
								<td style="font-family: sans-serif; font-size: 14px; vertical-align: top;" valign="top">	
									<p>
                                        <?= $lang->translate("your_account_has_been_locked")?>
                                    </p>
									<h4>
                                        <?= $lang->translate("this_action_as_taken_in_response")?>
                                    </h4>
                                    <?= $lang->translate("to_unlock_your_account")?>
									<p>
                                        <?= $lang->translate("for_your_security_your_account")?>
                                    </p><br>
									<p>
                                        <?= $lang->translate("we_will_be_happy_to_assist")?>
                                    </p>
								</td>
							</tr>
						</table>
						<!-- END MAIN CONTENT -->

					</div>

					<!-- Footer -->
					<?php include(sprintf("%s%sfooter.phtml", dirname(__DIR__, 1), DIRECTORY_SEPARATOR)); ?>
					<!-- END Footer -->

				</td>

				<td style="font-family: sans-serif; font-size: 14px; vertical-align: top;" valign="top">&nbsp;</td>
			</tr>
		</table>
	</body>
</html>